### ISSUE TITLE
Page's `skip` option to be set at runtime

### ISSUE THREAD

**Issue by nagyrobi** [clydebarrow/esphome#116]
Ability to change `skip` value at runtime in:
```yaml
lvgl:
  pages:
    - id: page_remote_stuff
      skip: false
```

Maybe with something like:
```yaml
    - lvgl.page.update:
        id: page_remote_stuff
        skip: true
```

Use case: to allow or disallow access to certain pages depending on requirements, like
- only show heating controls page during winter
- hide pages controlling remote entities while HA is down/rebooting
- ...
