### ISSUE TITLE
Extra widgets suggestion

### ISSUE THREAD

**Issue by nagyrobi** [clydebarrow/esphome#12]
Don't know if you plan to add all the widgets but I'd suggest these:
- [x] **lv_animimg**, compared to simple image only difference is that instead of one source image, you set an array of multiple source images. A flashing status icon, or battery charging for example.
- [ ] **lv_colorwheel**, a color picker to set colors for lights.
- [x] **lv_keyboard**, enter Wi-Fi credentials :smile:
- [x] **lv_led**, simple indicator for something ON or OFF
- [ ] **lv_menu**, menus are popular in ESPHome, there's one for lcd displays so here is a must I guess
- [x] **lv_spinbox**, this is mandatory for thermostats
- [x] **lv_spinner**, I use this for my fan spinning speed visualisation, rotation speed can be customized
- [ ] **qrcode**, for generation of QR Codes at runtime

Not sure about
- [x] **lv_msgbox**
- [ ] **lv_win**
These should be called with some actions...

**Comment by nielsnl68** [comment]
The **lv_msgbox** is for sure interested to show notifications on the screen.
There is already a PR that added this functionality and can be used like:

```yaml
binary_sensor:
  - platform: gpio
    pin: GPIO0
    name: "Notificatiom Button"
    on_press:
      then:
       - lvgl.notification:
          title: "Hello World"
          message: "Please, brush your teeth every day."
          buttons: ["Done","Not Today"]
          on_return: 
             then:
                if:
                 condition:
                     lambda: |-
                         return  x== "Done"
                 then:
                   ... # do something`
```

I hope @clydebarrow can add it soon.
