### ISSUE TITLE
Import of SVG files not working correctly with LVGL

### ISSUE THREAD

**Issue by agillis** [clydebarrow/esphome#120]
**Describe the bug**
If you use and SVG with the image: command and set use_transparency: true most all anti-aliasing is removed from the image. I'm not sure if this is just because the LVGL code only supports RGB565 or another issue.

**To Reproduce**
use and SVG with use_transparency: true
This is my test

```
image:
  - file: https://esphome.io/_static/logo-text-on-light.svg
    id: boot_logo
    type: RGB565
    resize: 470x95
    use_transparency: true
```    

**Expected behavior**
Image should be clear on the background with only the transparent part replaced with the background color

**Screenshots**
See my bug https://github.com/esphome/issues/issues/6047

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
