### ISSUE TITLE
`display_id` option

### ISSUE THREAD

**Issue by nagyrobi** [clydebarrow/esphome#17]
```
            "display_id": {
              "key": "Required",
              "is_list": true,
              "type": "schema",
              "maybe": "display_id",
              "schema": {
                "config_vars": {
                  "display_id": {
                    "key": "Required",
                    "use_id_type": "display::Display",
                    "type": "use_id"
                  }
                }
              }
            },
```

requires config like:

```yml
  display_id:
    - display_id: vnc_display
    - display_id: tft_display
```

It would look better like

```yml
  displays:
    - display_id: vnc_display
    - display_id: tft_display
```

But also, if the node has only one display configured, use it by default and this whole config item could be omitted - thus optional.
