### ISSUE TITLE
Actions

### ISSUE THREAD

**Issue by nagyrobi** [clydebarrow/esphome#20]
I find it that there are too many actions registered to change some specific properties.

There's the powerful 
`lvgl.obj.update`
action to change properties/styles/states/flags of the widget main parts:
```
      - lvgl.obj.update:
          id: day_label
          bg_color: 0x00FF00
          state:
            disabled: false
```

And there are actions like
`lvgl.checkbox.update`
`lvgl.label.update`
`lvgl.arc.update`
`lvgl.roller.update`
to change properties/styles/states/flags of certain widget's subparts.
```yml
      - lvgl.label.update:
          id: day_label
          text: "Something"
```
Or even
`lvgl.indicator.line.update`
to change properties/styles/states/flags of certain widget's parts of the subparts.
```yml
      - lvgl.indicator.line.update:
          id: minute_hand
          value: 10
```
Are these intended to be like shorthands?

Wouldn't it make sense to structure everything under `lvgl.obj.update` (moreover, something simpler like `lvgl.update`) and nest the subparts hierarchically?

like:
```
      - lvgl.update:
          id: minute_hand
          line_color: 0x00FF00
          state:
            disabled: false
          indicator:  #could only be specifict to what the widget supports, eg. knob etc.
            value: 10
```
or
```
      - lvgl.update:
          id: day_label
          bg_color: 0x00FF00
          state:
            disabled: false
          text: "Something"  #additional widget-specific options just added at the same level as the main ones
```

These would:
- make the understandability easier
- update properties of main and subparts in one go instead multiple subsequent actions
- less code to maintain...
