### ISSUE TITLE
`select` obj

### ISSUE THREAD

**Issue by nagyrobi** [clydebarrow/esphome#23]
select:
  - platform: lvgl
    name: LVGL Select
    **dropdown**: dropdown_id

should be `obj` instead of `dropdown`

**Comment by clydebarrow** [comment]
No, because it can either be a dropdown or a roller, but nothing else.

**Comment by nagyrobi** [comment]
OK, but at `switch` you have:
```
switch:
  - platform: lvgl
    obj: checkbox_id  # or btn_id
    name: LVGL switch
```
Supported widgets are `btn` and `checkbox`.

I'd say that to be consistent, you'd have at `select` similarly
```
select:
  - platform: lvgl
    obj: dropdown_id # or roller_id
    name: LVGL Select
```
