### ISSUE TITLE
`img` options and transparency tests

### ISSUE THREAD

**Issue by nagyrobi** [clydebarrow/esphome#25]
From https://docs.lvgl.io/8.3/widgets/core/img.html some options:
- Transparency (correlation with ESPHome's image transparency possibilities?)
- Recolor (`img_recolor_opa` adn `img_recolor` similar to `bg_*`)
- Mosaic
- Offset
- Rounded image
- Transformations (if not already done)

**Comment by nagyrobi** [comment]
Supported encodings?

**Comment by nagyrobi** [comment]
Some tests:

```yaml
        - obj:  # background for test transparency
            id: color_matte
            x: 0
            y: 40
            width: 240
            height: 240
            bg_color: 0x00ffff
            bg_opa: cover
            radius: 0
            pad_all: 0
            border_width: 0
            widgets:
              - img:
                  align: center
                  src: esphome_logo_transparent
                  id: img_transp
```
with:

```yaml
image:
  - file: https://esphome.io/_static/made-for-esphome-black-on-transparent.png
    id: esphome_logo_transparent
    resize: 220x72
    type: # as below
    use_transparency: # as below
```
with `type: TRANSPARENT_BINARY` (transparency enabled by default) results in:
![kép](https://github.com/clydebarrow/esphome/assets/1550668/4629d354-1299-4c9f-b470-e820bdcc8fb7)

with `type: GRAYSCALE` results in (same result with `dither: FLOYDSTEINBERG`):
![kép](https://github.com/clydebarrow/esphome/assets/1550668/87b98a0a-2781-4764-a5e8-766713c3af33)

with: `type: GRAYSCALE` and `use_transparency: true` results in (nothing):
![kép](https://github.com/clydebarrow/esphome/assets/1550668/33479823-2e91-478f-8840-ede787673633)

with `type: RGB565` results in:
![kép](https://github.com/clydebarrow/esphome/assets/1550668/4dbfbaf5-049e-4507-8efb-7ddca990c14c)

with `type: RGB565` and `use_transparency: true` results in:
![kép](https://github.com/clydebarrow/esphome/assets/1550668/60f184e6-3ef8-45b8-a9b6-15efe62e0ae6)

with: `type: RGB24` results in:
![kép](https://github.com/clydebarrow/esphome/assets/1550668/f41d5d9a-8058-4030-931f-a320e36a082f)

with: `type: RGB24` and `use_transparency: true` results in:
![kép](https://github.com/clydebarrow/esphome/assets/1550668/f41d5d9a-8058-4030-931f-a320e36a082f)

with: `type: RGBA` (transparency enabled by default) results in:
![kép](https://github.com/clydebarrow/esphome/assets/1550668/f41d5d9a-8058-4030-931f-a320e36a082f)

**Comment by nagyrobi** [comment]
Repeated some of the tests with SVG image instead of PNG:

```yaml
image:
  - file: https://esphome.io/_static/made-for-esphome-black-on-transparent.svg
    id: esphome_logo_transparent
    resize: 220x72
    type: # as below
    use_transparency: # as below
```
with `type: TRANSPARENT_BINARY` (transparency enabled by default) results in:
![kép](https://github.com/clydebarrow/esphome/assets/1550668/60f184e6-3ef8-45b8-a9b6-15efe62e0ae6)

with: `type: GRAYSCALE` and `use_transparency: true` results in (nothing):
![kép](https://github.com/clydebarrow/esphome/assets/1550668/33479823-2e91-478f-8840-ede787673633)

with `type: RGB565` and `use_transparency: true` results in:
![kép](https://github.com/clydebarrow/esphome/assets/1550668/60f184e6-3ef8-45b8-a9b6-15efe62e0ae6)

**Comment by nagyrobi** [comment]
I think situation is similar to the fonts, LVGL seems to use a proprietary format, and they have online and offline converter tools for images to C arrays: https://lvgl.io/tools/imageconverter

It's two approaches here: 
- the command line tool can be used before compile, like _pillow_ or _cairo_ are used (add another `type: LVGL` with sub-options maybe?)
- some other implementation needs to be done at runtime for https://github.com/clydebarrow/esphome/issues/14

**Comment by nagyrobi** [comment]
Scenario for tests. Save this transparent PNG as `inc/g64.png`.
![g64](https://github.com/clydebarrow/esphome/assets/1550668/de340ab2-8af1-40c2-9b33-a2d980983050)

Configure in ESPHome:
```yaml
image:
  - file: "inc/g64.png"
    id: transp01
    type: RGB565
  - file: "inc/g64.png"
    id: transp02
    type: RGB565
    use_transparency: true
  - file: "inc/g64.png"
    id: transp03
    type: RGB24
  - file: "inc/g64.png"
    id: transp04
    type: RGB24
    use_transparency: true
  - file: "inc/g64.png"
    id: transp05
    type: RGBA
```

```yaml
lvgl:
  ...
    - id: page_imgs
      skip: false
      pad_all: 0
      bg_color: 0xadab00
      border_width: 3
      y: 30
      widgets:
        - img:
            x: 10
            y: 10
            src: transp01
            id: img_transp01
        - label:
            text: RGB565
            align_to:
              id: img_transp01
              align: OUT_BOTTOM_MID

        - img:
            src: transp02
            id: img_transp02
            align_to:
              id: img_transp01
              align: OUT_RIGHT_TOP
              x: 10
        - label:
            text: RGB565+T
            align_to:
              id: img_transp02
              align: OUT_BOTTOM_MID

        - img:
            src: transp03
            id: img_transp03
            align_to:
              id: img_transp02
              align: OUT_RIGHT_TOP
              x: 10
        - label:
            text: RGB24
            align_to:
              id: img_transp03
              align: OUT_BOTTOM_MID

        - img:
            src: transp04
            id: img_transp04
            align_to:
              id: img_transp03
              align: OUT_RIGHT_TOP
              x: 10
        - label:
            text: RGB24+T
            align_to:
              id: img_transp04
              align: OUT_BOTTOM_MID

        - img:
            src: transp05
            id: img_transp05
            align_to:
              id: img_transp04
              align: OUT_RIGHT_TOP
              x: 10
        - label:
            text: RGBA
            align_to:
              id: img_transp05
              align: OUT_BOTTOM_MID
```

Result:
![kép](https://github.com/clydebarrow/esphome/assets/1550668/b23acd14-c70c-4139-a4db-d1106de1f1b6)

In the log:
```
[I][lvgl:000]: [Warn]   (944197.437, +944197437)         lv_img_decoder_built_in_open: Image decoder open: unknown color format         (in lv_img_decoder.c line #464)
[I][lvgl:000]: [Warn]   (944197.437, +0)         _lv_img_cache_open: Image draw cannot open the image resource  (in lv_img_cache.c line #125)
[I][lvgl:000]: [Warn]   (944197.437, +0)         lv_draw_img: Image draw error  (in lv_draw_img.c line #84)
[I][lvgl:000]: [Warn]   (944197.437, +0)         lv_img_decoder_built_in_open: Image decoder open: unknown color format         (in lv_img_decoder.c line #464)
[I][lvgl:000]: [Warn]   (944197.437, +0)         _lv_img_cache_open: Image draw cannot open the image resource  (in lv_img_cache.c line #125)
[I][lvgl:000]: [Warn]   (944197.437, +0)         lv_draw_img: Image draw error  (in lv_draw_img.c line #84)
[I][lvgl:000]: [Warn]   (944197.437, +0)         lv_img_decoder_built_in_open: Image decoder open: unknown color format         (in lv_img_decoder.c line #464)
[I][lvgl:000]: [Warn]   (944197.437, +0)         _lv_img_cache_open: Image draw cannot open the image resource  (in lv_img_cache.c line #125)
[I][lvgl:000]: [Warn]   (944197.437, +0)         lv_draw_img: Image draw error  (in lv_draw_img.c line #84)
```

**Comment by clydebarrow** [comment]
Transparency now works, e.g.
```
image:
  - file: image.png
    resize: 200x200
    type: RGB565
    use_transparency: true
    id: image_png
```
