### ISSUE TITLE
`arc` Place another object to the knob

### ISSUE THREAD

**Issue by nagyrobi** [clydebarrow/esphome#31]
This is a real kickass feature: https://docs.lvgl.io/8.3/widgets/core/arc.html#place-another-object-to-the-knob
See the Simple Arc example at the bottom of the page.

![Névtelen](https://github.com/clydebarrow/esphome/assets/1550668/8191fec6-7889-4799-b953-676464172a24)

Should be feasible with a choice from two config options:
```yml
    - arc:
        x: 10
        y: 10
        id: arc_id
        value: 75
        min_value: 1
        max_value: 100
        adjustable: true
        align_obj_to_angle:  # this or the other
          obj_to_align: id_of_the_other_object
          radius_offset: distance_wanted_from_the_arc
        rotate_obj_to_angle:
          obj_to_rotate: id_of_the_other_object
          radius_offset: distance_wanted_from_the_arc
```
