### ISSUE TITLE
Antiburn function

### ISSUE THREAD

**Issue by nagyrobi** [clydebarrow/esphome#33]
Not strongly a LVGL feature, rather something that could probably be achieved on a `canvas` with a lambda:
https://github.com/HASwitchPlate/openHASP/issues/134
https://github.com/HASwitchPlate/openHASP/blob/0ebfe7dcef4a9d01e10e0ad86005ae17289c6986/src/hasp_gui.cpp#L109

TLDR: LCD/TFT/OLED screens showing the same picture constantly will burn in the pixels not relaxing periodically. To prevent this, it's a recommendation to periodically train them with random RGB pixels (say, for 1 minute per day).

**Comment by nielsnl68** [comment]
This is very easy to do now:

```yaml

esphome:
  on_boot:
    priority: 10
    then:
      - script.execute: my_script
  
touchscreen:
  - platform: ...
    ...
    on_touch:
      then:
        - script.execute: my_script

  # Define a PWM output on the ESP32
output:
  - platform: ledc
    pin: 16
    id: gpio_17_backlight_pwm
  
# Define a monochromatic, dimmable light for the backlight
light:
  - platform: monochromatic
    output: gpio_17_backlight_pwm
    name: Backlight
    id: back_light
    restore_mode: ALWAYS_OFF

script:
  - id: my_script
    mode: restart
    then:
      - light.turn_on: back_light
      - lvgl.resume
      - delay: 10min
      - light.turn_off: back_light
      - lvgl.pause
```

**Comment by nagyrobi** [comment]
How does that draw random RGB pixels?

**Comment by clydebarrow** [comment]
```
            on_...:
              then:
                - lvgl.pause:
                    show_snow: true
```

Will fill the screen with random pixels until LVGL is unpaused.
Would probably want to also dim the backlight.

**Comment by nagyrobi** [comment]
Not sure how complicated would be to extend this with something like 
```
show_snow: 
  time: 600s
  end_color: 0xFFFFFF
```
to just show the snow for a certain amount of time and white out after that. A daily cycle of 10-15 minutes of snow is enough to train the pixels, not sure if this causes some CPU/BUS stress, power increase or not, might be worth having an option to stop after a while.

**Comment by nielsnl68** [comment]
I think that the option to turn off the screen after some small time prevent the screen from burning in, is it not?

**Comment by nagyrobi** [comment]
> I think that the option to turn off the screen after some small time prevent the screen from burning in, is it not?

Not. For these panels, when you "turn off" the screen, in reality you just turn off the backlight. The pixels in the LCD panel layer are still showing the picture, you just don't see it because it's not being lit. Burn in happens at pixel level, it's independent of backlight (more influenced by ambient temperature).

Read 
https://github.com/HASwitchPlate/openHASP/issues/134#issuecomment-816760577 for more details.

**Comment by clydebarrow** [comment]
> to just show the snow for a certain amount of time and white out after that

Just use the same mechanism as used to enter the paused state, e.g. in my L8:

```
time:
  - platform: sntp
    id: esptime
    timezone: Australia/Sydney
    on_time:
      - seconds: 0
        minutes: 30
        hours: 0
        then:
          - lvgl.pause:
              show_snow: true
    on_time:
      - seconds: 0
        minutes: 30
        hours: 2
        then:
          - lvgl.resume:
```

Combined with resume on touch, just in case I'm having a post-midnight snack:

```
touchscreen:
  - platform: ....
    id: my_touchscreen
    on_release:
      then:
        - if:
            condition: lvgl.is_paused
            then:
              - lvgl.resume:
```

CPU time etc used is not significant - it only updates one row of pixels per loop() interval, so likely running at 5% utilisation.
