### ISSUE TITLE
Possible new issue with handling **bineary_sensors**

### ISSUE THREAD

**Issue by nielsnl68** [clydebarrow/esphome#35]
I'm just wondering of this is still valid:

```yaml
binary_sensor:
  - platform: lvgl
    name: light_totom
    obj: lv_button0
```

when i touch a button, LVGL is showing that i press the button but HA does not get notified,
