### ISSUE TITLE
options for `btnmatrix`

### ISSUE THREAD

**Issue by nagyrobi** [clydebarrow/esphome#38]
`one_checked` option from: https://docs.lvgl.io/8.3/widgets/core/btnmatrix.html#one-check

It's for making possible to check only one button from the matrix. When you toggle a button, the others will be "de-toggled". 
It would also be nice to complement this feature with the `select` functionality.

also we need `on_value` trigger to retrieve in x the ID of the button that was pressed.

**Comment by clydebarrow** [comment]
> `one_checked` option from: https://docs.lvgl.io/8.3/widgets/core/btnmatrix.html#one-check

Already implemented.

> we need on_value trigger to retrieve in x the ID of the button that was pressed.

Why? Each button in a button matrix can have its own actions. Although internally they are different to regular buttons, this is masked via the yaml config.

**Comment by nagyrobi** [comment]
> Why? Each button in a button matrix can have its own actions. Although internally they are different to regular buttons, this is masked via the yaml config.

For the users to easier implement something like [key_collector](https://esphome.io/components/key_collector.html) to design an alarm input panel for example. With `on_value` you could use the same action to receive the different button presses...

It's like when you need to input a sequence of numbers like a pin code - without having to define complicated scripts to concatenate incoming strings located in global variables.
Actually, `key_collector` is a pretty well thought out component for this purpose. Maybe we could make `btnmatrix` work with it?

Also see https://github.com/clydebarrow/esphome/issues/34#issuecomment-1889288429

**Comment by nagyrobi** [comment]
> > `one_checked` option from: https://docs.lvgl.io/8.3/widgets/core/btnmatrix.html#one-check
> 
> Already implemented.

Tested, config passes through the schema, but doesn't have any effect. Multiple buttons can stay checked.

**Comment by clydebarrow** [comment]
> Actually, `key_collector` is a pretty well thought out component for this purpose. Maybe we could make `btnmatrix` work with it?

Or maybe make `key_collector` work with LVGL.

**Comment by clydebarrow** [comment]
> ested, config passes through the schema, but doesn't have any effect. Multiple buttons can stay checked.

Fixed.

**Comment by nagyrobi** [comment]
> Or maybe make `key_collector` work with LVGL.

I think both need to know about each other @ssieb

**Comment by ssieb** [comment]
If the `btnmatrix` provides the `key_provider` interface, then it will work automatically.

**Comment by nagyrobi** [comment]
@ssieb Can you point out a sample in the code?

**Comment by ssieb** [comment]
Check out the `wiegand` and `matrix_keypad` components for example.  It's very simple.

**Comment by nagyrobi** [comment]
@clydebarrow maybe we could add a config option `key_provider: true` to btnmatrix root, and simply provide the texts put on the buttons to it as keys (and not allow symbols in this case).

**Comment by clydebarrow** [comment]
That will work, no need for the config option, and it will just send the first character of the button label (key_provider can only send single characters.)

**Comment by ssieb** [comment]
Symbols are fine.  If you want to send more than a single character, then just call the send method multiple times.

**Comment by nagyrobi** [comment]
@ssieb symbols here are graphical elements, not just *# keys.

@clydebarrow I thought about config option because one may use multiple btnmatrix instances (eg page navigation etc) and likely wouldn't want to use key_provider with those.

**Comment by clydebarrow** [comment]
Symbols in the LVGL world are just Unicode strings.

The btnmatrix won't send any keys unless it's connected to a key_collector.

**Comment by ssieb** [comment]
The key interface only handles `uint8_t` right now because it originally came from the keypad component.  It could be expanded, but I'm not sure how useful that would be.  What would you be using the keys for?
This should probably be a discord discussion. :-)

**Comment by nagyrobi** [comment]
> The btnmatrix won't send any keys unless it's connected to a key_collector.

Oh, you'd put at `source_id` the btnmatrix id?

**Comment by ssieb** [comment]
Yes.  As with most things in esphome, if there's only one source, it will pick it up automatically, but otherwise, you need to specify the source id.

**Comment by clydebarrow** [comment]
> If the `btnmatrix` provides the `key_provider` interface, then it will work automatically.

Done. Works a treat.

**Comment by nagyrobi** [comment]
Please reopen this, I'm trying to print the keys to a label but it won't compile:
```yaml
key_collector:
  - id: pincode_reader
    source_id: lvgl_keypad
    min_length: 4
    max_length: 4
    end_keys: "#"
    end_key_required: true
    back_keys: "*"
    allowed_keys: "0123456789"
    timeout: 5s
    on_progress:
      - logger.log:
          format: "input progress: '%s', started by '%c'"
          args: [ 'x.c_str()', "(start == 0 ? '~' : start)" ]
      - lvgl.label.update:
          id: keypad_label
          text: !lambda 'return str_sprintf("%s", x.c_str());'
          border_color: 0
    on_result:
      - logger.log:
          format: "input result: '%s', started by '%c', ended by '%c'"
          args: [ 'x.c_str()', "(start == 0 ? '~' : start)", "(end == 0 ? '~' : end)" ]
      - lvgl.label.update:
          id: keypad_label
          text: !lambda 'return str_sprintf("%s", x.c_str());'
          border_color: 0xFF0000
    on_timeout:
      - logger.log:
          format: "input timeout: '%s', started by '%c'"
          args: [ 'x.c_str()', "(start == 0 ? '~' : start)" ]
      - lvgl.label.update:
          id: keypad_label
          text: !lambda 'return str_sprintf("%s", x.c_str());'
          border_color: 0
```
fails to compile:
```
<unicode string>: In lambda function:
<unicode string>:1612:34: error: 'x' was not declared in this scope
<unicode string>: In lambda function:
<unicode string>:1620:34: error: 'x' was not declared in this scope
<unicode string>: In lambda function:
<unicode string>:1628:34: error: 'x' was not declared in this scope
```
It seems the result of the keycollector is available in the logger action but not the LVGL action.
