### ISSUE TITLE
`lvgl.widget.update` for btnmatrix buttons

### ISSUE THREAD

**Issue by nagyrobi** [clydebarrow/esphome#39]
How to update btnmatrix button properties/styles?

```
              - lvgl.widget.update: 
                  
                  ID 'cov_1_up' of type lvgl::LvBtnmBtn doesn't inherit from LvObjType. Please double check your ID is pointing to the correct value.
                  id: cov_1_up
```

**Comment by clydebarrow** [comment]
```
                    then:
                      - lvgl.button.update:
                          id: button_a
                          width: 1
                          selected: true
                          control:
                            checkable: false
```

Only those attributes may be updated (i.e. not text or symbol.)
