### ISSUE TITLE
Escape characters in texts, eg. `label`

### ISSUE THREAD

**Issue by nagyrobi** [clydebarrow/esphome#40]
`label` supports multiline texts: https://docs.lvgl.io/8.3/widgets/core/label.html#newline
`\n` should start a new line. Currently:

```
        - label:
            align: center
            id: lbl_id
            y: 30
            recolor: true
            text: 'Write a #ff0000 red# word\nand a #0000ff blue# one'
```
produces:  
![kép](https://github.com/clydebarrow/esphome/assets/1550668/8c40b8e6-d85f-4b93-93d4-f402bc6bff28)
looks like `\n` is interpreted textually, not being escaped.

Other escape sequences like `\u`, `\U` [should be supported](https://github.com/clydebarrow/esphome/issues/4#issuecomment-1893295713) on long term...

Also LVGL supports formatting with `printf` which is also ESPHome-friendly: https://docs.lvgl.io/8.3/widgets/core/label.html#set-text this could be usable when updating labels from lambdas.

Maybe some configurable options would be needed? Like `escape_chars: true` and `use_printf: true`?
