### ISSUE TITLE
`meter` needle/line styling

### ISSUE THREAD

**Issue by nagyrobi** [clydebarrow/esphome#41]
According to this: https://docs.lvgl.io/8.3/widgets/extra/meter.html#parts-and-styles

> LV_PART_INDICATOR The needle *line* or image *using the line* and img *style properties*, as well as the background properties to draw a square (or circle) on the pivot of the needles. Padding makes the square larger.

Trying to set the needle to be `hidden` but config is not accepted:

```yaml
        - meter:
            align: center
            scales:
              - ticks:
                  width: 1
                  count: 81
                  length: 5
                  color: 0x000000
                  major:
                    stride: 10
                    width: 2
                    length: 8
                    color: 0xC0C0C0
                    label_gap: 8
                range_from: -30
                range_to: 50
                angle_range: 240
                rotation: 150
                indicators:
                  - line:
                      id: temperature_needle
                      width: 2
                      color: 0xFF0000
                      r_mod: -4
                  hidden: true #not accepted
                    hidden: true #not accepted
                      hidden: true #not accepted


```
Also I wonder what action could be used to set needle properties at runtime? `lvgl.indicator.line.update` or `lvgl.widget.update` are not suitable atm.

Use case: hide the needle when value coming from HA is invalid (aka. `nan` `unknown` `unavailable`). This is usually the case when the node boots but HA is not yet connected, when HA reboots and disconnects, or there's a network problem. A few automations handling these cases would hide the needle to avoid displaying invalid data. Would start with the needle in hidden state and when the first valid value comes in, show it with an action.

If `hidden` can't work, `line_width: 0` could do it (tried, same). Or maybe delete/create if possible.

**Comment by nagyrobi** [comment]
`lvgl.indicator.line.update` seems pretty special, maybe worth renaming to `lvgl.meter.needle.update`...?

**Comment by nagyrobi** [comment]
Also it would be nice to have `value` and `hidden` as a templatable options, like:
```yml
                indicators:
                  - line:
                      id: temperature_needle
                      width: 2
                      color: 0xFF0000
                      r_mod: -4
                      value: !lambda |-
                        if (!std::isnan(id(my_sensor).state)) {
                          return id(my_sensor).state;
                        }
                      hidden: !lambda |-
                        return std::isnan(id(my_sensor).state);
```
