### ISSUE TITLE
`state` options templatable

### ISSUE THREAD

**Issue by nagyrobi** [clydebarrow/esphome#43]
To implement like this:
```
        - btn:
            checkable: true
            id: button_light
            state:
              checked: !lambda |-
                return id(ha_light_binary_sensor).state;
```
instead of tedious `on_state`/`on_click` automations at the binary sensor...

**Comment by nielsnl68** [comment]
That would make my live much easier :D

**Comment by nagyrobi** [comment]
Yeah also stuff like:
```yaml
            state:
              disabled: !lambda |-
                return !id(ha_available).state;
```
To prevent interactions with widgets related to remote entities through HA, if disconnected.
