### ISSUE TITLE
Outside alignment not working

### ISSUE THREAD

**Issue by nagyrobi** [clydebarrow/esphome#47]
```yaml
        - img:
            x: 10
            y: 170
            src: cat_image
            id: img_id
            radius: 11
            clip_corner: true
            widgets:
              - label:
                  id: lbl_cathome
                  align: OUT_BOTTOM_MID
                  text: 'Home'
                  text_color: 0xFF0000
```
results in
![kép](https://github.com/clydebarrow/esphome/assets/1550668/4f6905cd-416d-45b2-9dc4-c43f8b62cde6)

Expectation is to have the text under the picture because of `align: OUT_BOTTOM_MID`.
Ref: 
https://docs.lvgl.io/8.3/widgets/obj.html#alignment
https://docs.lvgl.io/8.3/overview/coords.html#align

**Comment by clydebarrow** [comment]
A child widget is clipped to its parent boundaries anyway, so setting an OUT alignment will never work (and is in fact ignored.)

I've updated the schema to disallow OUT values on `align:` and added `align_to:` to allow a widget to be aligned to another.
The two objects should be siblings.

```
        - img:
            x: 10
            y: 200
            src: cat_image
            id: img_id
            radius: 11
            clip_corner: true
        - label:
            id: lbl_cathome
            align_to:
              id: img_id
              x: 0
              y: 5
              align: OUT_BOTTOM_MID
            text: 'Home'
            text_color: 0x00FF00
```
The x and y are optional and default to 0.
