### ISSUE TITLE
Selecting `dropdown` `roller` `btnmatrix` items by item name

### ISSUE THREAD

**Issue by nagyrobi** [clydebarrow/esphome#52]
There is:
```
    - lvgl.dropdown.update:
        id: dropdown_id
        selected_index: 3
```
which is good if we know the index number.

The corresponding HA integrations which could be used with these widgets use states which show not the index, but the name of the currently selected option.

We need a shortcut/wrapper for the action above which could be able to resolve the index from the name, something like:
```
    - lvgl.dropdown.select:
        id: dropdown_id
        item_name: Bassoon
```

Use case: with a text sensor we can retrieve the current state name from HA, and with the just call `lvgl.**.select` with `item_name` parameter to select the item with the same name.

**Comment by clydebarrow** [comment]
Can you provide an example for this? The select entity exposed to HA uses an index, not a string. Setting the value via an arbitrary text value might not work, as it would have to match exactly, so what should happen if it matches none of the options?

**Comment by nagyrobi** [comment]
I may have ran a bit fast... :)

End goal is to present in LVGL a dropdown, roller or btnmatrix mirroring a select from HA corresponding to some other integration. Like in the examples from the [cookbook](https://deploy-preview-3510--esphome.netlify.app/cookbook/lvgl#remote-light-button), you use a switch widget in LVGL to toggle an arbitrary light switch in HA, or adjust various other entities, you need to retrieve their state first from HA with `platform: homeassistant` kind of sensor first.

For example you have in HA a `select.ventilation_system` (provided by some other integration) with some presets:

```yaml
options:
  - Base
  - Mid
  - High
  - Turbo
  - Off
icon: mdi:fan
friendly_name: Ventilation presets
```
This select's state can only be a textual value, one of the options listed eg. state: `Base`

We could create a  dropdown, roller or btnmatrix in LVGL with exactly these options (also see https://github.com/clydebarrow/esphome/issues/46):
```yaml
lvgl:
   ...
        - dropdown:
            id: vent_dropdown
            options:
              - Base
              - Mid
              - High
              - Turbo
              - Off
```
and a text sensor to retrieve the state, which would have to use a resolution function to update the dropdown't selected value by the name, since there's no index available:
```yaml
text_sensor:
  - platform: homeassistant
    id: ventilation_system_select_state
    entity_id: select.ventilation_system
    on_value:
      - lvgl.dropdown.select:
          id: vent_dropdown
          item_name: !lambda return x.c_str(); #or similar
```

> what should happen if it matches none of the options

Nothing, just a warning in ESPHome log (the chances to occur would be minimized if https://github.com/clydebarrow/esphome/issues/46 would be possible).

Moreover, if we would have `on_value` for dropdown/roller/btnmatrix, we could do the reverse, update the select in HA based on the choice made here as described in https://github.com/clydebarrow/esphome/issues/49.

**Comment by clydebarrow** [comment]
Just use a select linked to the roller/dropdown, and use automations in HA to sync with something else.
```
select:
  - platform: lvgl
    dropdown: lv_dropdown
    name: LVGL Dropdown
```
