### ISSUE TITLE
Default font setting

### ISSUE THREAD

**Issue by nagyrobi** [clydebarrow/esphome#54]
Currently it seems the default font is globally hardcoded to `montserrat_14`. Although a different font can be set individually at the widgets or in theme/style defs, it would be nice if it would simply be possible to override the global default for the widgets not using any of these.

Perhaps at `lvgl` root level something like `default_text_font`.

Reason: lvgl default font only supports ASCII.

**Comment by nagyrobi** [comment]
Another reason, even if manually specifying a different font for every used widget, the default font will still be compiled in, as that's the one used to print system messages (like eg. `No data` when an image can't be loaded), using extra memory space. Which could be saved by specifiying as default a font which will be used anyway.

**Comment by nagyrobi** [comment]
Implemented, but currently only with built-in fonts.

Workaround (as these are the widgets using fonts):
```yaml
  theme:
    label:
      text_font: your_esphome_fond_id
    btnmatrix:
      items:
        text_font: your_esphome_fond_id
```
