### ISSUE TITLE
Background image

### ISSUE THREAD

**Issue by nagyrobi** [clydebarrow/esphome#58]
Options to set _display_ (not widget) backdround image/color/opacity:

https://docs.lvgl.io/8/overview/display.html#background

**Comment by clydebarrow** [comment]
`disp_bg_color:` is working, `disp_bg_image` is not currently.

**Comment by clydebarrow** [comment]
Now working.

**Comment by nagyrobi** [comment]
```yaml
color:
  - id: color_pink
    hex: ff00ff

lvgl:
...
  disp_bg_color: color_pink #nor 0xff00ff
```

results in:

```
Compiling .pioenvs/esp32-test-lvgl-host/src/main.o
config/_02_host_lvgl_5_demos.yaml: In lambda function:
config/_02_host_lvgl_5_demos.yaml:2327:37: error: could not convert ‘color_pink’ from ‘esphome::Color’ to ‘lv_color_t’ {aka ‘lv_color16_t’}
*** [.pioenvs/esp32-test-lvgl-host/src/main.o] Error 1
```
