### ISSUE TITLE
`dropdown` list styling

### ISSUE THREAD

**Issue by nagyrobi** [clydebarrow/esphome#60]
Can't find the options to customize styling of the list elements of `dropdown`.

`text_font:` only affects the dropdown label, not the list:

![kép](https://github.com/clydebarrow/esphome/assets/1550668/299d7185-2446-4adc-b3fe-d8955f983804)

Adjusting height of the `dropdown` doesn't center the text in the middle, so I guess some padding styles are needed too.

**Comment by clydebarrow** [comment]
```
        - dropdown:
            indicator:
              text_font: helv20
            id: lv_dropdown
            options:
              - First
              - Second
              - Third
            selected_index: 2
            dir: top
            symbol: ${arrow_down}
            dropdown_list:
              bg_color: color_blue
              text_color: 0x800000
```
