### ISSUE TITLE
`checkbox` wrong in theme, taking `btn` styles

### ISSUE THREAD

**Issue by nagyrobi** [clydebarrow/esphome#61]
The config below doesn't apply the settings for `checkbox` to the checkbox, it applies the settings of `btn` for the checkbox:
```yaml
  theme:
    label:
      text_font: robi_20
    btn:
      bg_color: 0x2F8CD8
      bg_grad_color: 0x005782 
      bg_grad_dir: VER
      bg_opa: cover
      border_color: 0x0077b3
      border_width: 1
      text_color: 0xFFFFFF
      pressed:
        bg_color: 0x006699
        bg_grad_color: 0x00334d
      checked:
        bg_color: 0x1d5f96
        bg_grad_color: 0x03324A
        text_color: 0xfff300
    checkbox:
      border_color: 0xC0C0C0
      indicator:
        text_font: montserrat_14
      checked:
        bg_color: 0xC0C0C0
```
