### ISSUE TITLE
`obj` not clipping children

### ISSUE THREAD

**Issue by nagyrobi** [clydebarrow/esphome#62]
If i have a child widget wider than the width set, scrollbar will appear at the bottom.
```
        - obj:
            x: 5
            y: 35
            pad_all: 0
            width: 230
            max_width: 230 # same without this
            height: 250
            bg_opa: 0
            border_width: 1
            widgets:
              - checkbox:
                  id: chk_stat_6
                  text: "Pretty long blah blah blah to go wider than obj width"
                  x: 5
                  y: 5
```
According to LVGL doc

> Children can be visible only within their parent’s bounding area. In other words, the parts of the children outside the parent are clipped.

But this doesn't seem to be respected with `obj`.
Note that width is respected as the object itself is drawn at correct width.
