### ISSUE TITLE
`transform_angle`, `transform_zoom` failure

### ISSUE THREAD

**Issue by nagyrobi** [clydebarrow/esphome#71]
Was trying to rotate a label by 180 degrees.

```yaml
              - label:
                  text: "\U000F1C98"
                  text_font: icons_42
                  transform_angle: 180
                  align: CENTER
                  y: -14
```
resulted in:
```
[17:06:18][I][lvgl:000]: [Warn] (2228973.661, +7920)     lv_draw_sw_layer_create: Rendering this widget needs LV_COLOR_SCREEN_TRANSP 1  (in lv_draw_sw_layer.c line #47)
[17:06:18][I][lvgl:000]: [Warn] (2228973.661, +0)        refr_obj: Couldn't create a new layer context  (in lv_refr.c line #912)
```

According to https://docs.lvgl.io/8.3/overview/style-props.html?highlight=transform_angle#transform-angle The value is interpreted in 0.1 degree units. E.g. 450 means 45 deg. If I try 1800 I get  `value must be at most 360.0.` Do we apply a conversion to float here?

`transform_zoom` has the same issue, `translate_x` works, btw.
