### ISSUE TITLE
Formatted text for widget updates

### ISSUE THREAD

**Issue by clydebarrow** [clydebarrow/esphome#82]
**Is your feature request related to a problem? Please describe.**
When updating a label or other text item, it is nice to be able to format data

**Describe the solution you'd like**
Add a schema to implement:

```
     text:
		format: "%0.1f"
		arguments: [ x ]
```

**Comment by clydebarrow** [comment]
completed. E.g.
```
    on_value:
      then:
        - lvgl.label.update:
            id: wifi_label
            text:
              format: "%.0fdBm"
              args: [x]
```
Just like the logger.log usage.
