### ISSUE TITLE
Pagination implementation

### ISSUE THREAD

**Issue by nagyrobi** [clydebarrow/esphome#9]
Based on https://docs.lvgl.io/8.3/overview/object.html#screens

`pages:` element

inspired from [select](https://esphome.io/components/select/#select-next-action) concept, or [pages](https://esphome.io/components/display/#display-pages).

idea:
```yaml
pages_loop: true # wrap around to the first/last when doing next/previous
pages:  
  - page:
    master: true # the "master" page is a layer shown above all the other pages. 
    skip: false #skip this screen when doing next/previous (templatable)
    id: ...
    widgets:
      - ...
```

The `master` page is to hold eg. status widgets or navigation buttons which would always be visible regardless of active page, this would save us from duplicating them on/for every screen with automations etc. Only one master page is allowed!

Pages with `skip` option set could only be displayed with a dedicated `lvgl.page.show`, they don't show with `next` and `previous` actions. Use case is a boot logo, we would `show` such a skipped page on_boot, and after a delay `show` a default home page. Another use case is an advanced settings page , which could be shown with a button, and having a Back button on it to return to the page where it was triggered from.

actions:
```
lvgl.page.show
lvgl.page.next
lvgl.page.previous
lvgl.page.back # when jumping around, say, from a hidden page, which was shown with a button trigger
```

conditions:
`lvgl.is_displaying_page`

trigger:
`lvgl.on_page_change`

**Comment by nagyrobi** [comment]
Thanks for https://github.com/clydebarrow/esphome/commit/cec9698fc5d39f21df8aa8a89157bfe746c9867d!
Works!

There are use cases for selecting pages remotely, eg. display a page automatically when certain conditions are met in HA.

A way could be perhaps to populate a `select` component with the desired pages.  Having `restore_value` (like template select has), would allow to restore the active page after reboot. 

a usermap of pages...
```
select:
  pages:
    - page_1: Page 1
    - page_2: Page 2
    - the_id: The name
```
and the user just manually picks the pages added to it. When the user changes (on the display) to a page not configured in the select, nothing happens.
