### ISSUE TITLE
QR code

### ISSUE THREAD

**Issue by nagyrobi** [clydebarrow/esphome#91]
1. [ ] add [qr-code-component](https://esphome.io/components/display/#qr-code-component) to be usable as `src` in `img` and `animimg` widgets.
2. [ ] extend it to be able to generate QRs at runtime from strings. 

Perhaps as a [LVGL sub-module](https://docs.lvgl.io/8.4/libs/qrcode.html).

Both ESPHome and LVGL use [nayuki](https://github.com/nayuki/QR-Code-generator)'s library to generate QR codes, but ESPHome doesn't seem to be able to do it at runtime from a lambda:

```yaml
qr_code:
  - id: homepage_qr
    value: !lambda 'return to_string("esphome.io");'
```
results in:
```
qr_code: [source config/test.yaml:112]
  - id: homepage_qr

    This option is not templatable!.
    value: !lambda |-
      return to_string("esphome.io");
```
